entando/entando-cms

package-lock.json, package.json
also omitted @entando/router and instead added react-router to dependencies.
in order to install peer dependencies, install [npm-install-peers](https://www.npmjs.com/package/npm-install-peers) with `npm i -g npm-install-peers` then run `npm-install-peers` afterwards.
Let me know if I have missed some peer dependencies to add up.
=> EN6-52 Peer dependencies with apimanager and messages

src/state/__tests__/categories/actions.test.js, src/state/__tests__/categories/selectors.test.js, src/state/__tests__/rootReducer.test.js, src/state/categories/selectors.js, src/state/content-model/__tests__/actions.test.js, src/state/content-model/__tests__/selectors.test.js, src/state/content-model/selectors.js, src/state/content-type/__tests__/selectors.test.js, src/state/content-type/selectors.js, src/state/edit-content/__tests__/selectors.test.js, src/state/edit-content/selectors.js, src/state/rootReducer.js, src/testutils/mocks/categories.js, src/ui/__tests__/App.test.js, src/ui/content-model/__tests__/AddContentModelFormContainer.test.js, src/ui/content-model/__tests__/ContentModelListContainer.test.js, src/ui/content-model/__tests__/ContentModelListPage.test.js, src/ui/content-model/__tests__/EditContentModelFormContainer.test.js, src/ui/edit-content/__tests__/EditContentFormContainer.test.js
Please let me know if the way I coded in `rootReducer.js` is correct or not. Only 4 related reducers have been modified, `categories`, `editContent`, `contentModel`, and `contentType`. Other branches will be modified same to this concept once this PR has been approved/merged.
=> EN6-115 change the reducers base location in the state to apps/cms/*

package-lock.json, src/api/__tests__/editContent.test.js, src/api/editContent.js, src/state/categories/selectors.js, src/state/edit-content/__tests__/actions.test.js, src/state/edit-content/__tests__/reducer.test.js, src/state/edit-content/actions.js, src/state/edit-content/reducer.js, src/state/edit-content/types.js, src/testutils/mocks/editContent.js, src/ui/App.js, src/ui/add-content/AddContentFormContainer.js, src/ui/add-content/__tests__/AddContentFormContainer.test.js, src/ui/add-content/__tests__/AddContentPage.test.js, src/ui/categories/common/CategoryTreeSelector.js, src/ui/categories/common/CategoryTreeSelectorContainer.js, src/ui/categories/common/CategoryTreeSelectorRow.js, src/ui/edit-content/EditContentForm.js, src/ui/edit-content/EditContentFormContainer.js
Change logic of handling the categories provided by single content. That's why the tests are now updated and new tests are added. Fetching a single content is still an issue, because of that whole content list is fetched and one of them is chosen for editing.
=> Implement EditContent page

src/sass/common/CMSShell.scss
The fix is just by overriding the Patternfly style for active menu items in a persistent secondary navbar. It seems that they didn't consider a mix of multi-level menu items and single-level ones as the corresponding style appears to be only suitable for multi-level items.
=> EN6-92 Fix CMS menu height issue

src/ui/common/link-config/LinkConfigContentForm.js, src/ui/common/link-config/LinkConfigContentFormContainer.js, src/ui/common/modal/LinkConfigModal.js
Previous implementation used `form` for assigning a content. Unfortunately content list container paginator was also using `form`, so HTML error form under form is not acceptable was thrown in dev console. That's why I re-implemented with div instead of form and manually triggered submit via `mapDispathcToProps`.
=> ENG-125 change default form via div

src/ui/edit-content/content-attributes/BooleanAttributeField.js
Fixes boolean attribute not reflecting API response value when editing a content.
=> ENG-369 Always convert BooleanAttributeField input value to string

src/ui/content-type/AddContentTypeForm.js
Hi @gidesan @joewhite101 ,
this commit fixes a bug  on the Content types edit/add page , the "Default content template for lists" was always set to "No template".
Could you please have a look?
Thanks
=> ENG-527: fixes default content model list field name

package-lock.json, package.json, src/state/pages/__tests__/actions.test.js, src/state/pages/__tests__/reducer.test.js, src/state/pages/actions.js, src/state/pages/reducer.js, src/state/pages/types.js, src/ui/common/page/PageTreeSelectContainer.js
This PR is marked as draft because once `frontend-libraries` has a newer version of `pagetreeselector` its version also needs to be bumped up in`entando-cms`.
=> ENG-519 implement cms side for expand/collapse all

src/state/assets/__tests__/selectors.test.js, src/state/assets/selectors.js
on edit asset cropping - error occurs when saving protected asset because structure of filename has been modified (on `versions` key), so this needs to be using the name in "File Name" of  asset's metadata map
=> ENG-466 asset filename retrieval basis refactored

src/ui/common/form/FiltersSelectRenderer.js, src/ui/widget-forms/ContentsQueryConfig.js, src/ui/widget-forms/ContentsQueryConfigContainer.js
`key` prop of a `filter` is being used on adminconsole's CMS widget setting but on app-builder - it's using `code` instead of `key`. so I used the `key` as the actual form field in app-builder (instead of `code`) but when its field change event is invoked, it will set the `code` field same as `key` field.
=> ENG-542 CMS widget list of contents filter value not showing

src/ui/common/form/FiltersSelectRenderer.js, src/ui/widget-forms/ContentsQueryConfig.js, src/ui/widget-forms/ContentsQueryConfigContainer.js
frontend filter choices are now added with selected content type attributes that are marked for list filters (`listFilter`). Also restored the resetFilterOption function on widget config
=> ENG-659 - frontend filter choices for CMS widget

src/babel.js, src/state/__tests__/rootReducer.test.js, src/state/contents/__tests__/actions.test.js, src/state/contents/__tests__/reducer.test.js, src/state/contents/__tests__/selectors.test.js, src/state/contents/actions.js, src/state/contents/reducer.js, src/state/contents/selectors.js, src/state/contents/types.js, src/state/rootReducer.js, src/state/table-columns/__tests__/actions.test.js, src/state/table-columns/__tests__/reducer.test.js, src/state/table-columns/__tests__/selectors.test.js, src/state/table-columns/actions.js, src/state/table-columns/reducer.js, src/state/table-columns/selectors.js, src/state/table-columns/types.js, src/ui/common/content/Contents.js, src/ui/common/content/ContentsContainer.js, src/ui/contents/Contents.js, src/ui/contents/ContentsContainer.js, src/ui/contents/ContentsTabs.js, src/ui/widget-forms/contents-filter/ContentsFilterModalContainer.js, src/ui/widget-forms/contents-filter/ContentsFilterTabs.js
- Export `table-columns` as separate redux property (took out from `contents` state, as its used several other places too)
- Export `persistData` for usage in `app-builder` to maintain preferred contents table columns list
=> ENG-716 table columns

src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
default current columns for content table display of the content table for widget configs was missed after #215 was merged.
=> ENG-543 missed default current column array prop

src/locales/en.js, src/ui/assets/AssetsList.js
The API is expecting the type `file` and we were sending `documents` instead.
=> ENG-797: CMS/Digital Assets: "Documents" tab shows nothing after long running spinner

src/helpers/__tests__/joinGroups.test.js, src/helpers/joinGroups.js, src/state/assets/actions.js, src/ui/widget-forms/ContentPickerContainer.js
Seems that join groups are sometimes returned as a string. At this moment we cannot doing a deep refactor, so I only tried to make the join groups retrieval more robust.
cc @ichalagashvili @jeffgo10
=> ENG-996 fix content list widget settings

src/ui/edit-content/EditContentForm.js
it makes the Owner Groups disabled only for on edit mode:
=> making ownerGroup enabled when adding a new content

src/ui/edit-content/EditContentForm.js
in the previous PR I added `&& workMode === WORK_MODE_EDIT` to not call `onSetOwnerGroupDisable` unnecessarily, but `ownerGroupDisabled` was also being used on `showAllSettings` variable that was responsible to show the other groups after selecting the owner group.
I'm fixing it by removing the extra condition.
=> fixing add content screen

src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
caught a little bug on not filling up the config fields on single content widget config form while page refresh
=> ENG-722 singleconfigcontent on page refresh parameters fix

src/state/edit-content/actions.js
duplicate values are only for purely text-based attributes
=> ENG-1580 no duplicate for image attribute values

src/ui/contents/ContentsFilter.js
Use object spread instead of property assignment when forming a new object from props to prevent unexpected behavior
=> ENG-1623 Avoid mutating props in ContentsFilter

package-lock.json, src/api/__tests__/users.test.js, src/api/users.js, src/state/users/__tests__/actions.test.js, src/state/users/__tests__/reducer.test.js, src/state/users/__tests__/selectors.test.js, src/state/users/actions.js, src/state/users/reducer.js, src/state/users/selectors.js, src/state/users/types.js, src/testutils/mocks/editContent.js, src/testutils/mocks/users.js, src/ui/add-content/AddContentFormContainer.js, src/ui/add-content/__tests__/AddContentFormContainer.test.js, src/ui/edit-content/EditContentForm.js, src/ui/edit-content/content-attributes/AttributeFields.js
* Sets the default content owner group to a value derived from the user preferences. If there's no value, this sets the content owner group to be the group in which the user has the admin role (extracted from the user authorities).
* Sets the default content join groups to an array of values derived from the user preferences.
=> ENG-1688 Implement Default Content Owner Group and Join Groups

package-lock.json, src/ui/assets/AssetsListContainer.js, src/ui/categories/filter/CategoryTreeFilterContainer.js, src/ui/categories/filter/CategoryTypeaheadFilter.js
toggle categories in the array functionality (in asset filter reducer) has been recently removed from the previous PRs and this particular control above the assets list which is active filter chip set is presumably relying on the toggle function reducer. this PR resolves it by using a special toggle in an array function before going to the reducer
=> ENG-2302 resolve issue on removing active filter tag above asset list

src/ui/assets/AssetsList.js
The redux-form actions being triggered at search(and anything else on this screen) is making the assets component to rerender(and refetching the images from a cache). This issue should be the main reason for bad performance described in this ticket, I couldn't find anything else as I don't have that many data on my local env.
Issue without the fix:
after the fix:
=> ENG-2198: preventing unnecessary component rerender

src/ui/common/modal/GenericModal.js, src/ui/common/modal/GenericModalContainer.js, src/ui/widget-forms/publish-single-content-config/SingleContentConfigContainer.js, src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
I found out this issue when I was working on cypress test on editing widget config for single content. when changing content in an existing single content widget, modal automatically closes before it could even load the list of contents to choose from. Also amended the recent change for generic modal component from app-builder.
=> ENG-2496 resolve issue on involuntary close modal in single content widget config

package-lock.json, src/helpers/attrValidation.js, src/ui/edit-content/content-attributes/AttributeField.js, src/ui/edit-content/content-attributes/AttributeFields.js
* Fixes validation logic
* Adds resolver function as 2nd arg to `memoize()` in order to have a proper cache key
* Passes `defaultLang` into `linkValidate()` to avoid the field validation being overridden by another with a different `langCode`
=> ENG-2608 Fix content link validation
