jsconfig.json
package-lock.json
package.json
src/api/__tests__/login.test.js
src/api/login.js
src/app-init/ApiManager.js
src/app-init/__tests__/ApiManager.test.js
src/index.js
src/state/__tests__/rootReducer.test.js
src/state/rootReducer.js
src/ui/ApiManager.js

From what I understood, this is only implemented for development, standalone app running purposes. So I've used `admin` account to auto-login if username/token are not found in localStorage. Working parent of this branch is EN6-52 (see #1 for PR info).

EN6-46 implement auto login

---

README.md

Changelog
- installation prerequisites for developers
- added details on code specs

Readme updated for developers guide

---

package.json
src/ui/App.js

Add a ROUTE_CMS into main routes array and assign defaultRedirect to it.

EN6-120 add main route in the array

---

src/ui/App.js
src/ui/add-content/AddContentPage.js
src/ui/content-model/AddContentModelPage.js
src/ui/content-model/ContentModelListPage.js
src/ui/content-model/EditContentModelPage.js
src/ui/content-model/__tests__/AddContentModelPage.test.js
src/ui/content-model/__tests__/ContentModelListPage.test.js
src/ui/content-model/__tests__/EditContentModelPage.test.js
src/ui/content-settings/ContentSettingsPage.js
src/ui/content-settings/__tests__/ContentSettingsPage.test.js
src/ui/content-type/AddContentTypePage.js
src/ui/content-type/ContentTypeListPage.js
src/ui/content-type/EditContentTypePage.js
src/ui/content-type/__tests__/ContentTypeListPage.test.js
src/ui/content-type/attributes/AddContentTypeAttributePage.js
src/ui/content-type/attributes/EditContentTypeAttributePage.js
src/ui/content-type/attributes/monolist/MonolistPage.js
src/ui/edit-content/EditContentPage.js

technically this is just moving `<CMSShell>` component outside the route pages

EN6-119 move top menu outside of routes

---

src/sass/modules.scss

removing relational css url to work with app-builder as a plugin

Fix on css relativity issue from build with cms integration

---

src/state/assets/__tests__/selectors.test.js
src/state/assets/selectors.js
src/ui/assets/AssetsList.js
src/ui/assets/AssetsListContainer.js
src/ui/assets/AssetsListGridView.js
src/ui/assets/AssetsListItem.js

- refactoring on adding domain to the image URLs. This was refactored due to case on using relative URL in domain env. See comments in https://jira.entando.org/browse/EN6-80
- All URL joining processes has been moved to `state/assets/selector` to clear processes in ui components
- unit test updated

EN6-80 from photo cropping - domain prefix refactoring

---

src/sass/content-model/AddContentModelForm.scss

fix on not showing content model assistant dialog when pressing the assistant button

EN6-176 content model form dialog fix

---

src/sass/assets/AssetPhotoCropper.scss
src/sass/assets/AssetsList.scss
src/sass/assets/AssetsListGridView.scss
src/sass/categories/filter/CategoryTreeFilter.scss
src/sass/content-model/AddContentModelForm.scss
src/state/categories/__tests__/actions.test.js
src/state/categories/actions.js
src/testutils/mocks/categories.js
src/ui/assets/AssetsList.js
src/ui/assets/AssetsListContainer.js
src/ui/assets/AssetsListGridView.js

shows a "regeneratorRuntime" error when integrated to app-builder. Solve it on replacing async/await with dispatches/promises. Also fixed some Assets section CSS error. Related unit tests updated

EN6-175 Fix on runtime error in assets/content section when CMS is integrated

---

src/ui/content-type/AddContentTypeFormContainer.js
src/ui/content-type/EditContentTypeFormContainer.js
src/ui/content-type/__tests__/EditContentTypeFormContainer.test.js

resulted to reset all selected attributes every edit / add content type attribute form

EN6-180 content type anomalies fix

---

src/state/contents/actions.js

BE change: right now NEW and DRAFT status both can be presented. Also, author filter is performed via "firstEditor". This PR addresses those changes.

EN6-83 wrap up content list task

---

src/state/assets/actions.js

Change the way digital assets fetch query is generated. Remove query creator string and perform params assembling manually.

EN6-114 fix AND filter for categories

---

src/state/assets/actions.js
src/ui/assets/AssetsList.js
src/ui/assets/AssetsListContainer.js

Remove unused functions from container.
Fixed keyword searching functionality.

EN6-114 fix keyword search clash with categories

---

src/state/assets/__tests__/actions.test.js
src/state/assets/actions.js
src/ui/assets/AssetsList.js

- Fixes a bug when categories did not exist, code was trying to access it

EN6-193 handle no categories presented

---

src/ui/assets/AssetsList.js
src/ui/assets/AssetsListItem.js
src/ui/common/content/ContentList.js
src/ui/contents/ContentsTable.js

- Update asset list and content list screens so they show times too along with dates
- Change logic of showing sorting icons on asset list screen

EN6-114 change all dates to datetimes

---

src/locales/en.js
src/locales/it.js
src/ui/widget-forms/ContentPicker.js

This PR contains fixes for:
- ENG-134
- ENG-135

ENG-134 clarify more search criteria and change search disabling logic

---

package-lock.json
package.json
src/ui/widget-forms/HandpickedContentsConfigForm.js

This PR fixes:
- Logic of showing Publishing Settings for a single content widget form
- Fixes all of the vulnerabilities for CMS, even lows ( currently 0 vulns )

ENG-133 publishing settings fix for single content widget form

---

src/locales/en.js
src/locales/it.js
src/sass/common/form/ContentTypeAttributeForm.scss
src/sass/index.scss
src/ui/common/StickySave.js
src/ui/common/contenttype-attributes/AttributeListTable.js
src/ui/common/contenttype-attributes/AttributeListTableActions.js
src/ui/common/form/AddContentTypeAttributeForm.js
src/ui/common/form/EditContentTypeAttributeForm.js
src/ui/content-type/attributes/AddContentTypeAttributeFormContainer.js
src/ui/content-type/attributes/AddContentTypeAttributePage.js
src/ui/content-type/attributes/EditContentTypeAttributeFormContainer.js

- fulfill requirements in https://jira.entando.org/browse/ENG-142
- fix some repeated labels
- fix some file naming

ENG-142 Fix UX issues related to Content Types - Content Attributes editing

---

src/sass/assets/AssetsList.scss

-> Was "pushing" down the asset list inside the modal. Scroll was unavailable also.

ENG-146 Enable user to add image and attach files

---

src/ui/common/form/AddContentTypeAttributeForm.js
src/ui/common/form/EditContentTypeAttributeForm.js
src/ui/content-type/attributes/AddContentTypeAttributeFormContainer.js
src/ui/content-type/attributes/EditContentTypeAttributeFormContainer.js

- This PR takes care of ENG-171 (final feedback from Sabrina). When editing an attribute during edition of content type

ENG-171 add cancel confirmations to edit attributes of edit content type

---

src/state/edit-content/__tests__/actions.test.js
src/state/edit-content/actions.js

Includes decoupling serializing field values, list/composite serialization on listed types on the loop, unit tests

ENG-502 List/Monolist dates fix

---

package-lock.json
src/sass/assets/AssetsAdvancedFilter.scss
src/sass/assets/AssetsList.scss
src/sass/assets/UploadAsset.scss
src/ui/assets/AssetsUpload.js
src/ui/common/form/RenderDatePickerInput.js

This PR contains:
- DND small drop area bug fix
- CSS fixes for asset list advanced filter and table kebab button

ENG-550 dnd bug

---

package-lock.json
package.json
src/__tests__/babel.test.js
src/api/__tests__/permissions.test.js
src/api/permissions.js
src/app-init/ApiManager.js
src/app-init/routes.js
src/state/__tests__/rootReducer.test.js
src/state/permissions/__tests__/actions.test.js
src/state/permissions/__tests__/reducer.test.js
src/state/permissions/__tests__/selectors.test.js
src/state/permissions/actions.js
src/state/permissions/const.js
src/state/permissions/reducer.js
src/state/permissions/selectors.js
src/state/permissions/types.js
src/state/rootReducer.js
src/state/store.js
src/testutils/mocks/permissions.js
src/testutils/mocks/users.js
src/ui/__tests__/App.test.js
src/ui/common/LinkMenu.js
src/ui/common/StickySave.js
src/ui/common/auth/withPermissions.js
src/ui/contents/Contents.js
src/ui/contents/ContentsTable.js

- implemented permissions on content section
- added permissions state and other permission related helpers for local development

ENG-584 - permissions on actions on CMS

---

src/locales/en.js
src/locales/it.js
src/sass/common/form/FiltersSelectRenderer.scss
src/ui/widget-forms/ContentTableRenderer.js
src/ui/widget-forms/contents-filter/ContentsFilterBrowser.js
src/ui/widget-forms/contents-filter/ContentsFilterBrowserContainer.js
src/ui/widget-forms/contents-filter/ContentsFilterModal.js
src/ui/widget-forms/contents-filter/ContentsFilterModalContainer.js
src/ui/widget-forms/contents-filter/ContentsFilterTable.js

- component on selecting contents has been changed from autocomplete to regular contents table
- took the existing component from the other widget (select a content to publish) but decoupled the content table from the modal

ENG-543 publish contents widget config change on selecting contents

---

src/sass/contents/ContentsStatusCard.scss
src/sass/index.scss
src/ui/common/content/Contents.js
src/ui/common/content/ContentsContainer.js
src/ui/contents/status-card/ContentsStatusCard.js
src/ui/contents/status-card/ContentsStatusCardContainer.js

- Includes hotfix for columns showing in contents table

ENG-686 apply new changes

---

src/state/edit-content/actions.js
src/ui/edit-content/content-attributes/LinkAttributeField.js

also fix on clearing of image/attach content value when deleting

ENG-759 composite saving fix on link & date

---

src/ui/edit-content/content-attributes/AttachAttributeField.js
src/ui/edit-content/content-attributes/AttachAttributeFieldContainer.js
src/ui/edit-content/content-attributes/AttributeField.js
src/ui/edit-content/content-attributes/ImageAttributeField.js
src/ui/edit-content/content-attributes/ImageAttributeFieldContainer.js
src/ui/edit-content/content-attributes/assets/AssetAttributeFieldInfoContainer.js

metadatas/text desc are different per language

ENG-860 Asset (image/attach) content must have same source regardless of language

---

src/state/content-type/actions.js
src/ui/contents/list-card/ContentListCardContainer.js

fixing Content list tile to point to right state

ENG-991: Page dashboard tiles fixes

---

src/ui/add-content/AddContentFormContainer.js
src/ui/common/SectionTitle.js
src/ui/edit-content/EditContentForm.js
src/ui/edit-content/EditContentFormContainer.js

This PR makes sections of Add/Edit content page collapsable

ENG-1095 implement collapsable sections for ease of use

---

src/state/user-preferences/selectors.js

mocking userPreference state to not break the standalone app

ENG-1413: Fix `userPreferences` on standalone CMS app

---

src/ui/assets/AssetsListItem.js

implementing caching system to force img to refresh when a new version is available on the server

ENG-1429: Asset created by an admin doesn't update automatically after editing it

---

src/ui/contents/ContentsTable.js
src/ui/edit-content/content-attributes/LinkAttributeField.js

This PR contains:
- Fix existing Link text values being overwritten
- MenuItem fix to be unclickable if its disabled

ENG-1527 fix link text resetting

---

src/state/edit-content/actions.js
src/ui/common/StickySave.js
src/ui/edit-content/content-attributes/AttributeFields.js
src/ui/edit-content/content-attributes/ThreeStateAttributeField.js

Fixes the form being invalid if either boolean, checkbox, or threestate has a false/null value.

ENG-1590 Fix boolean, checkbox, threestate attribute field values

---

src/helpers/__tests__/attrValidation.test.js
src/helpers/attrValidation.js
src/ui/edit-content/content-attributes/AttributeField.js

this will not accept tag only attribute values

ENG-1585 RTE hypertext attribute resolve on empty values when field is mandatory

---

src/helpers/__tests__/attrValidation.test.js
src/helpers/attrValidation.js
src/ui/edit-content/content-attributes/AttributeField.js
src/ui/edit-content/content-attributes/LinkAttributeField.js

ENG-1606 Fix link attribute validation

---

src/ui/content-type/AddContentTypeForm.js

Reverts entando/entando-cms#327
this PR prevents the creation of content type and need further discussions

Revert "ENG-1563: making templates required on the content type screen"

---

src/ui/common/form/ContentTypeMonolistAttributeForm.js
src/ui/common/form/RenderListField.js

* adds missing settings section when adding a monotext list attribute
* fixes monotext list validation

ENG-1627 Fix monotext list form validation

---

package-lock.json
src/helpers/attrValidation.js

ENG-1668 Fix composite attribute validation causing app crash

---

package-lock.json
package.json

* Updates react-router-dom peer dependency to match app-builder version.
* Updates enzyme-adapter-react-16.

React router update

---

package-lock.json
package.json
src/state/contents/__tests__/reducer.test.js
src/state/contents/reducer.js

* Fix content nav not showing default active tab on search.
* Fix and add content reducer tests.
* Update node-sass to a version that supports Node 14.

ENG-2184 Fix content active tab on search

---

src/state/contents/actions.js

Fixes the issue where the search filters get ignored when switching to another tab.

ENG-2185 Fix content tab switch resetting search results

---

package-lock.json
src/state/contents/actions.js

Fix passed query param to the contents request URL by setting filter attribute status to `public` when fetching published contents.

ENG-2277 Fix fetching of published contents

---

src/ui/content-template/ContentTemplateList.js

Fix deleting the content template had no data correctly put into modal info

ENG-2377 fix content template deletion

---

src/state/categories/selectors.js
src/ui/categories/filter/CategoryTypeaheadFilter.js

this was from my previous merge regarding showing all the categories in UI category tree components in CMS

ENG-2308 showstopper resolve on displaying content list and assets list

---

src/ui/edit-content/content-attributes/AttributeFields.js

Merge ENG-2238 changes into ENG-2287

---

src/ui/widget-forms/ContentConfigFormBody.js
src/ui/widget-forms/ContentsQueryConfig.js
src/ui/widget-forms/ContentsQueryConfigContainer.js
src/ui/widget-forms/MultipleContentsConfigContainer.js

- if page link is selected, then default language link text should become mandatory

ENG-2412 make link text require if page selected
